version: "3.3"
# Список наших сервисов (контейнеров)
services:
    nginx:
      # используем последний стабильный образ nginx
        image: nginx:alpine
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
            - php2
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - database
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    php2:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php2
        # этот образ будет общаться с mysql
        links:
            - database
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    database:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: devops
            MYSQL_USER: devops
            MYSQL_PASSWORD: devops

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
          - database:db
        ports:
          - 8765:80
        environment:
          MYSQL_ROOT_PASSWORD: 123456
        depends_on:
          - database
